// Application constants

const ORDER_TYPES = {
  DINE_IN: 'DINE_IN',
  TAKEAWAY: 'TAKEAWAY',
  DELIVERY: 'DELIVERY',
};

const ORDER_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PREPARING: 'PREPARING',
  READY: 'READY',
  SERVED: 'SERVED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

const PAYMENT_METHODS = {
  CASH: 'CASH',
  CARD: 'CARD',
  DIGITAL_WALLET: 'DIGITAL_WALLET',
  UPI: 'UPI',
  BANK_TRANSFER: 'BANK_TRANSFER',
};

const TABLE_STATUS = {
  AVAILABLE: 'AVAILABLE',
  OCCUPIED: 'OCCUPIED',
  RESERVED: 'RESERVED',
  CLEANING: 'CLEANING',
  OUT_OF_ORDER: 'OUT_OF_ORDER',
};

const USER_ROLES = {
  TENANT_ADMIN: 'TENANT_ADMIN',
  MANAGER: 'MANAGER',
  CASHIER: 'CASHIER',
  WAITER: 'WAITER',
  KITCHEN_STAFF: 'KITCHEN_STAFF',
  DELIVERY_STAFF: 'DELIVERY_STAFF',
};

const SUBSCRIPTION_PLANS = {
  BASIC: 'BASIC',
  PREMIUM: 'PREMIUM',
  ENTERPRISE: 'ENTERPRISE',
};

const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  INSUFFICIENT_INVENTORY: 'INSUFFICIENT_INVENTORY',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  TENANT_ACCESS_DENIED: 'TENANT_ACCESS_DENIED',
  EXTERNAL_SERVICE_UNAVAILABLE: 'EXTERNAL_SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};

const INVENTORY_UNITS = {
  KG: 'KG',
  GRAM: 'GRAM',
  LITER: 'LITER',
  ML: 'ML',
  PIECE: 'PIECE',
  PACKET: 'PACKET',
  BOX: 'BOX',
};

module.exports = {
  ORDER_TYPES,
  ORDER_STATUS,
  PAYMENT_STATUS,
  PAYMENT_METHODS,
  TABLE_STATUS,
  USER_ROLES,
  SUBSCRIPTION_PLANS,
  ERROR_CODES,
  INVENTORY_UNITS,
};